In [1]:
import pandas as pd
import numpy as np

# New Section

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [6]:
df = pd.read_csv('residential_land.csv')

In [11]:
df.sample(1)

,property_name,link,society,price,areaWithType,address,floorNumAllowed,noOfOpenSides,possession,nearbyLocations,description,features,rating,property_id
2233,Residential land / Plot in Sector 99 Gurgaon,https://www.99acres.com/residential-land-plot-...,G99,4.47 Crore,(288 sq.m.) Plot Area,"N/a, Sector 99 Gurgaon, Gurgaon, Haryana",NaN,2.0,Immediate,"['The Hive Shopping Mall', 'Dwarka Expressway'...","G99 in sector-99 gurgaon, gurgaon by the uppal...","[['Feng Shui / Vaastu Compliant', 'Maintenance...","[['Environment4.5 out of 5', 'Lifestyle4 out o...",D69592276

In [12]:
df.drop(columns=['link','address','nearbyLocations','description','rating','property_id'], inplace=True)

In [18]:
df['society'].value_counts()

society
nan                                              1083
bptp amstoria                                      87
experion the westerlies                            72
central park flower valley                         57
g99                                                46
dlf alameda                                        31
ansals palam vihar                                 29
vatika xpressions                                  29
vatika express city                                29
vatika india next plots                            27
mrs 16 acres                                       27
emaar emerald hills                                26
orris woodview residencies                         26
central park flower valley mikasa plots            24
dlf gardencity                                     23
ansal api esencia                                  20
satya merano greens                                20
dlf city plots                                     18
bptp green oaks                                    17
raheja vanya                                       17
ansals shiva som valley                            17
bptp astaire gardens                               16
adani brahma samsara vilasa                        15
rof normanton park                                 14
dlf city plots phase 2                             13
malibu towne                                       13
rof insignia park 2                                13
paras ekam homes                                   12
emaar mgf marbella                                 12
unitech south city                                 11
adani oyster greens                                11
jms the nation                                     11
ireo city plots                                    11
vatika india next                                  10
breez flora avenue 88a                             10
mapsko aspr hills                                  10
vipul world                                        10
rof insignia park                                  10
nkv residential plots                               9
shyam kunj                                          9
vatika aspiration                                   9
ansal api versalia                                  9
adani m2k oyster grande                             9
sohna road                                          8
bptp fortuna                                        8
skywhales vienna greens                             7
corona greens                                       7
jms prime land                                      7
ace palm floors                                     6
shree vardhman city                                 6
rishali luxe residency 112                          6
unitech singleton floors                            6
india rashtra                                       6
ireo project                                        6
huda flats                                          6
ansal sushant lok 2                                 6
supertech hill town                                 6
ireo savannah                                       6
dlf garden city floors                              5
anant raj estate plots                              5
suncity township                                    5
dlf city plots phase 3                              5
supertech sambhav homes                             5
ardee city                                          5
raheja akshara                                      5
ireo savannah sector 35 sohna                       4
pyramid palm county                                 4
vatika one express city                             4
ansal                                               4
lion infra green valley                             4
ansal sushant lok plots                             4
anant raj estates                                   4
vatika one india next                               4
dlf city phase 1                                    4
vatika westin sohna resort                          4
dlf gardencity enclave                              4
unitech greenwood city                              4
landmark avana                                      4
rwa east pocket                                     3
ramprastha city                                     3
golden park                                         3
uppal southend                                      3
eros rosewood city                                  3
raheja aranya the green city                        3
jms mega city plots                                 3
village nakhdolla                                   2
nkv plots                                           2
saraswati kung                                      2
jawahar nagar                                       2
adani tatva estates, sector 99 gurugram             2
rwa sector 42                                       2
vrindavan city jamtha nagpur                        2
adani tatva estates                                 2
unitech uniworld resorts                            2
vaishnav enclave                                    2
vaishnav enclave phase2                             2
gokulam sector 7 sohna                              2
dlf city plots phase 4                              2
kuldeep avenue                                      2
orris aanandam ora sector 93                        2
huda sector 46                                      2
raheja vanya city                                   2
bharat residency dharam colony                      2
hero homes                                          2
shf homes                                           2
huda plots                                          2
jms the pride                                       2
rwa sector 46                                       2
ab realty the valencia                              2
orris atulyam 83                                    2
birla navya                                         2
pyramid spring valley                               2
aset sohna greens                                   2
mv buildcon precore city                            2
garden villas                                       2
ats home kraft                                      2
block c                                             2
ansal oriental villas                               2
true habitat 112                                    2
sector 52 gurgaon                                   2
1494 ap                                             2
silokhra saini khera                                2
dlf new town heights                                2
not applicable                                      2
rwa sector 43                                       1
rwa s ector 42                                      1
blite luxury floors                                 1
ansal florence residency                            1
d block                                             1
palda village, sector 70a, gurgaon                  1
ullawas sector 59, gurgaon                          1
imperial estate sector 70a, gurgaon                 1
sohna                                               1
sector 35                                           1
ansal royale casa                                   1
ansal plot palam vihar                              1
sadaa maruti kunj                                   1
sector 42 gurgaon                                   1
huda sector 1 pataudi                               1
sector 57                                           1
3b homes sector -95 gurgaon                         1
jms sohna sector -5                                 1
jms sohna saector -5                                1
sohna sector 35 ireo                                1
huda plots sector 57                                1
hero homes plot                                     1
jms the  megha city sector 5 sohna                  1
jms mega city sector 5 sohna                        1
adani brahma samsara                                1
supertech hill estate                               1
whiteland blissville                                1
atulyam-83                                          1
mapsko plots gurgaon                                1
pegasus atulyam 83                                  1
dlf the grove                                       1
3b home wal dovelopmnt                              1
sector 17                                           1
gold souk golf links                                1
sector 110a                                         1
vatika signature two                                1
landmark                                            1
dlf gardern city                                    1
nb gokulam                                          1
bst green bhoomi                                    1
ats bonheur avenue                                  1
huda sector 50                                      1
dlf south city 1                                    1
orris atulyam83                                     1
sushant  lok-1                                      1
vaishnav residency gurgaon                          1
vaishnav residency sector72a                        1
unitech palms south city 1                          1
vaishnav enclav badashpur                           1
vaishnav enclav badashapur                          1
unitech aspen greens                                1
huda housing board colony                           1
solutrean gateway 95                                1
paras trade centre                                  1
orris anandam sector 93                             1
urben estate huda  rwa sector-47 gurgaon            1
huda                                                1
experion the heartsong                              1
south city 1 plots                                  1
unitech deerwood chase                              1
hans enclave                                        1
ddjay true habitat sector 112                       1
nirmal kunj                                         1
s block dlf  phase 3                                1
vatika crossover                                    1
defence colony bhondsi                              1
krishna kunj                                        1
yash vihar                                          1
mortise gold golflink                               1
anand niketan                                       1
valencia sector 73                                  1
sushant lok 1 builder floors                        1
zara flora                                          1
ramprastha plots                                    1
vatika horizon sector 82 a                          1
vatika horizon sector 82a                           1
bnb nature valley                                   1
bhelpa greens                                       1
orchid island                                       1
3b homes pataudi one                                1
orris plot atulayam                                 1
sector-47                                           1
nul                                                 1
ansals florence villa                               1
unitech south city 2                                1
on request                                          1
vatika india next 2                                 1
adani tatva                                         1
naugaon ramgarh                                     1
sector 5 gurgaon                                    1
emaar emerald hills - phase 2                       1
dlf 1                                               1
ebd 89                                              1
vatika inxt 2                                       1
sector 10a                                          1
plaza 106                                           1
plot                                                1
radhe nagar colony                                  1
housing board colony                                1
savyasachi amaya greens                             1
raheja aranya phase il                              1
shree ram enclave                                   1
shri ram enclave                                    1
dlf garden city plot                                1
vtika express city plot sector-88b gurgaon          1
vaishnav kunj u block                               1
vaishnav kunj phase2                                1
ub-block badashpur                                  1
vaishnav kunj                                       1
vaishnav vaatika city                               1
vaishnav encivle                                    1
sector-57 gurgaon                                   1
sector-57                                           1
plot 60 sq yd 3 floors sushant lok sector  43       1
orris aanandam ora                                  1
sector-112                                          1
grover homes sec 46                                 1
sector 4                                            1
emreld hills                                        1
e block                                             1
m 1 block                                           1
omaxe plaza mall                                    1
asf isle de royale                                  1
dlf builder floors                                  1
hero homes earth                                    1
dlf gardencity, sector 92 gurgaon                   1
assotech breeze                                     1
luxe residency 112                                  1
wtc plaza 106                                       1
wtc plaza 106 ddjay                                 1
ireo sector 35                                      1
lakhuwas                                            1
shree vardhman softlaunch                           1
ashray apartment                                    1
kd realtek private limited                          1
sohna greens sector 5 sohna                         1
ireosavannah sector 35 sohna                        1
ireo savannah ddjay sector 35 sohna                 1
floora avenue                                       1
north east huda plot                                1
north east facing                                   1
north east plot                                     1
dlf the aralias                                     1
anant raj ashok estate                              1
grand central 114                                   1
delhi infratech de nest                             1
nirvana cedar crest                                 1
dlf city plots phase 5                              1
sector 22 gurugram                                  1
om kunj society gurgaon                             1
inderpuri                                           1
Name: count, dtype: int64

In [17]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [20]:
df['price'].value_counts()

price
4.5 Crore           37
1.25 Crore          25
1.8 Crore           23
1.2 Crore           23
3 Crore             22
4 Crore             22
5.5 Crore           21
2.5 Crore           20
5 Crore             20
8 Crore             19
3.5 Crore           18
6.5 Crore           18
7.5 Crore           18
5.25 Crore          17
9 Crore             17
6 Crore             17
3.75 Crore          16
Price on Request    16
1.6 Crore           15
15 Lac              15
7 Crore             15
80 Lac              15
1.1 Crore           14
2.6 Crore           14
2 Crore             14
2.2 Crore           14
1.4 Crore           13
60 Lac              13
1.5 Crore           13
3.8 Crore           13
1 Crore             13
4.6 Crore           12
2.7 Crore           12
3.4 Crore           12
3.1 Crore           12
10 Crore            12
2.1 Crore           12
4.2 Crore           12
3.25 Crore          11
1.35 Crore          11
3.6 Crore           10
4.8 Crore           10
8.5 Crore           10
1.7 Crore           10
2.4 Crore           10
3.3 Crore           10
1.75 Crore          10
90 Lac              10
2.9 Crore           10
2.3 Crore            9
2.25 Crore           9
1.32 Crore           9
5.1 Crore            9
4.25 Crore           9
9.5 Crore            9
4.4 Crore            9
2.15 Crore           9
1.3 Crore            9
65 Lac               9
2.75 Crore           9
1.9 Crore            8
6.25 Crore           8
1.15 Crore           8
8.25 Crore           8
4.75 Crore           8
3.2 Crore            8
1.65 Crore           7
3.24 Crore           7
8.75 Crore           7
18 Lac               7
3.13 Crore           7
75 Lac               7
12.5 Crore           7
3.7 Crore            7
30 Lac               7
2.16 Crore           6
10.5 Crore           6
7.5 Lac              6
2.58 Crore           6
1.72 Crore           6
2.55 Crore           6
13 Crore             6
3.85 Crore           6
4.1 Crore            6
2.8 Crore            6
25 Lac               6
1.82 Crore           6
6.75 Crore           6
7.25 Crore           6
3.9 Crore            6
1.13 Crore           6
4.99 Crore           5
2.05 Crore           5
3.35 Crore           5
4.3 Crore            5
14 Crore             5
1.57 Crore           5
4.47 Crore           5
1.85 Crore           5
7.1 Crore            5
5.7 Crore            5
9.25 Crore           5
17 Lac               5
1.43 Crore           5
1.96 Crore           5
5.35 Crore           5
2.45 Crore           5
50 Lac               5
1.24 Crore           5
5.85 Crore           5
2.35 Crore           5
40 Lac               5
35 Lac               5
1.61 Crore           5
3.45 Crore           5
1.04 Crore           5
3.65 Crore           5
5.3 Crore            5
11 Crore             5
3.15 Crore           5
7.2 Crore            5
9.2 Crore            5
96 Lac               5
1.92 Crore           4
4.24 Crore           4
1.28 Crore           4
2.99 Crore           4
4.72 Crore           4
4.45 Crore           4
7.8 Crore            4
2.09 Crore           4
12 Lac               4
1.93 Crore           4
5.9 Crore            4
17.5 Crore           4
11.25 Crore          4
5.4 Crore            4
1.86 Crore           4
10.76 Crore          4
2.64 Crore           4
2.18 Crore           4
16.5 Crore           4
2.34 Crore           4
95 Lac               4
85 Lac               4
1.98 Crore           4
16 Crore             4
2.91 Crore           4
1.17 Crore           4
6.15 Crore           4
12 Crore             4
1.45 Crore           4
4.79 Crore           4
1.05 Crore           4
1.33 Crore           4
2.26 Crore           4
5.65 Crore           4
5.6 Crore            4
3.48 Crore           4
1.78 Crore           4
12.7 Crore           4
1.47 Crore           4
1.06 Crore           4
63 Lac               4
15 Crore             4
16 Lac               4
4.46 Crore           4
4.08 Crore           4
1.21 Crore           4
5.8 Crore            4
6.6 Crore            4
1.95 Crore           4
2.77 Crore           4
7.75 Crore           4
2.52 Crore           4
1.26 Crore           4
2.95 Crore           4
4.9 Crore            4
21 Crore             4
1.12 Crore           3
4.38 Crore           3
24 Lac               3
3.05 Crore           3
28 Lac               3
4.7 Crore            3
1.81 Crore           3
5.64 Crore           3
47 Lac               3
1.67 Crore           3
1.02 Crore           3
1.63 Crore           3
6.11 Crore           3
1.68 Crore           3
1.58 Crore           3
11.5 Crore           3
2.85 Crore           3
1.88 Crore           3
3.64 Crore           3
4.49 Crore           3
21 Lac               3
2.47 Crore           3
3.5 Lac              3
3.04 Crore           3
3.71 Crore           3
42 Lac               3
5.2 Crore            3
6.45 Crore           3
1.27 Crore           3
4.12 Crore           3
66 Lac               3
4.48 Crore           3
11.29 Crore          3
1.97 Crore           3
1.08 Crore           3
3.88 Crore           3
12.6 Crore           3
5.05 Crore           3
4.35 Crore           3
2.38 Crore           3
32 Crore             3
2.08 Crore           3
4.15 Crore           3
5.26 Crore           3
1.38 Crore           3
8.4 Crore            3
7.15 Crore           3
1.73 Crore           3
72 Lac               3
2.63 Crore           3
3.47 Crore           3
3.59 Crore           3
1.22 Crore           3
10.25 Crore          3
2.53 Crore           3
9.75 Crore           3
3.94 Crore           3
8.28 Crore           3
70 Lac               3
5.55 Crore           3
6.18 Crore           3
11.6 Crore           3
3.31 Crore           3
11.8 Crore           3
55 Lac               2
25.5 Crore           2
3.68 Crore           2
4.87 Crore           2
4.97 Crore           2
1.34 Crore           2
6.3 Crore            2
2.98 Crore           2
4.69 Crore           2
7.49 Crore           2
6.9 Crore            2
1.48 Crore           2
2.24 Crore           2
4.16 Crore           2
4.55 Crore           2
37.6 Lac             2
3.49 Crore           2
6.05 Crore           2
1.01 Crore           2
4.65 Crore           2
7.99 Crore           2
8.2 Crore            2
1.16 Crore           2
2.04 Crore           2
2.32 Crore           2
6.78 Crore           2
48 Lac               2
2.36 Crore           2
5.21 Crore           2
5.95 Crore           2
2.87 Crore           2
8 Lac                2
74 Lac               2
2.84 Crore           2
2.92 Crore           2
3.78 Crore           2
26.5 Lac             2
5.01 Crore           2
6.85 Crore           2
5.04 Crore           2
37 Lac               2
1.44 Crore           2
87 Lac               2
3.51 Crore           2
93 Lac               2
14.5 Crore           2
3.96 Crore           2
2.57 Crore           2
4.85 Crore           2
3.63 Crore           2
1.76 Crore           2
3.29 Crore           2
3.33 Crore           2
13.5 Crore           2
33 Lac               2
9.1 Crore            2
31 Crore             2
6.65 Crore           2
6.4 Crore            2
5.09 Crore           2
1.09 Crore           2
2.07 Crore           2
5.13 Crore           2
4.95 Crore           2
4.09 Crore           2
5.47 Crore           2
30 Crore             2
2.79 Crore           2
3.62 Crore           2
1.55 Crore           2
31 Lac               2
1.71 Crore           2
6.8 Crore            2
76 Lac               2
2.12 Crore           2
20 Crore             2
3.01 Crore           2
3.19 Crore           2
26 Lac               2
6.1 Crore            2
3.72 Crore           2
3.67 Crore           2
4.01 Crore           2
45 Lac               2
2.51 Crore           2
5.66 Crore           2
7.35 Crore           2
2.28 Crore           2
4.64 Crore           2
3.92 Crore           2
11.1 Crore           2
54 Lac               2
29 Lac               2
6.03 Crore           2
88 Lac               2
46 Lac               2
56 Lac               2
6.53 Crore           2
2.48 Crore           2
2.97 Crore           2
2.96 Crore           2
2.83 Crore           2
8.53 Crore           2
1.79 Crore           2
3.52 Crore           2
6.64 Crore           2
5.92 Crore           2
8.8 Crore            2
2.23 Crore           2
1.89 Crore           2
3.89 Crore           2
1.46 Crore           2
82.5 Lac             2
2.88 Crore           2
2.13 Crore           2
4.05 Crore           2
2.03 Crore           2
23.5 Lac             2
89.6 Lac             2
22.71 Crore          2
2.67 Crore           2
3.26 Crore           2
19 Crore             2
2.86 Crore           2
2.73 Crore           2
28 Crore             2
5.76 Crore           1
49.5 Lac             1
1.36 Crore           1
7.96 Crore           1
5.07 Crore           1
76.8 Lac             1
3.93 Crore           1
3.21 Crore           1
2.81 Crore           1
6.55 Crore           1
4.04 Crore           1
12.66 Crore          1
4.34 Crore           1
4.28 Crore           1
4.81 Crore           1
6.34 Crore           1
10.54 Crore          1
2.54 Crore           1
3.06 Crore           1
5.52 Crore           1
23 Lac               1
1.49 Crore           1
4.39 Crore           1
4.13 Crore           1
3.38 Crore           1
3.37 Crore           1
1.53 Crore           1
9.05 Crore           1
8.14 Crore           1
16.25 Crore          1
13.18 Crore          1
93.75 Lac            1
6.06 Crore           1
92 Lac               1
6.61 Crore           1
7.42 Crore           1
8.3 Crore            1
7.26 Crore           1
4.89 Crore           1
3.39 Crore           1
10.55 Crore          1
8.95 Crore           1
3.34 Crore           1
7.97 Crore           1
3.41 Crore           1
2.29 Crore           1
3.22 Crore           1
1.87 Crore           1
12.55 Crore          1
5.94 Crore           1
13.27 Crore          1
6.19 Crore           1
98.01 Lac            1
10.49 Crore          1
5.98 Crore           1
3.28 Crore           1
17.56 Lac            1
25.87 Lac            1
16.89 Lac            1
15.24 Lac            1
14.53 Lac            1
17.51 Lac            1
20.55 Lac            1
16.52 Lac            1
15.64 Lac            1
10.5 Lac             1
11.3 Lac             1
60 Crore             1
1.29 Crore           1
1.56 Crore           1
6.12 Crore           1
95.2 Lac             1
1.03 Crore           1
88.5 Lac             1
5.75 Crore           1
3.17 Crore           1
5.46 Crore           1
12.93 Crore          1
14.4 Lac             1
16.2 Lac             1
12.1 Crore           1
2.21 Crore           1
20.3 Crore           1
11.7 Lac             1
4.53 Crore           1
6.28 Crore           1
2.01 Crore           1
2.68 Crore           1
6.09 Crore           1
66.5 Lac             1
5.24 Crore           1
9.4 Crore            1
81 Lac               1
1.19 Crore           1
100 Crore            1
4.14 Crore           1
2.76 Crore           1
2.06 Crore           1
5.96 Crore           1
24 Crore             1
13.2 Crore           1
7.3 Crore            1
8.6 Crore            1
4.26 Crore           1
1.64 Crore           1
19.75 Crore          1
4.11 Crore           1
18.5 Lac             1
4.21 Crore           1
5.36 Crore           1
30.7 Lac             1
6.52 Crore           1
22.44 Lac            1
4.59 Crore           1
46.5 Lac             1
7.18 Crore           1
81.26 Lac            1
58.45 Lac            1
12.11 Crore          1
82 Lac               1
1.11 Crore           1
1.62 Crore           1
11.75 Crore          1
8.54 Crore           1
5.51 Crore           1
5.53 Crore           1
7.54 Crore           1
8.46 Crore           1
11.03 Crore          1
7.45 Crore           1
34.2 Lac             1
27.52 Lac            1
26.96 Lac            1
84.7 Lac             1
2.42 Crore           1
9.19 Crore           1
8.55 Crore           1
8.45 Crore           1
4.73 Crore           1
6.68 Crore           1
4.02 Crore           1
10.6 Crore           1
97.6 Lac             1
97.75 Lac            1
4.63 Crore           1
11.71 Crore          1
5.78 Crore           1
49.75 Lac            1
98 Lac               1
4.86 Crore           1
22.4 Lac             1
5.74 Crore           1
22 Crore             1
4.03 Crore           1
6.96 Crore           1
7.38 Crore           1
1.95 Lac             1
6.93 Crore           1
6.24 Crore           1
11.2 Crore           1
31.5 Lac             1
26.52 Lac            1
17.5 Lac             1
27.2 Lac             1
64.8 Lac             1
4.76 Crore           1
7.48 Crore           1
6.7 Crore            1
10.2 Crore           1
5.49 Crore           1
8.1 Crore            1
3.98 Crore           1
13.25 Crore          1
30.75 Crore          1
1.39 Crore           1
62.22 Lac            1
11.15 Crore          1
19.5 Crore           1
6.02 Crore           1
7.65 Crore           1
23.5 Crore           1
9.11 Crore           1
29.75 Crore          1
11.38 Crore          1
3.79 Crore           1
14.31 Crore          1
7.6 Crore            1
4.44 Crore           1
6.29 Crore           1
6.84 Crore           1
10.8 Crore           1
2.61 Crore           1
9.15 Crore           1
7.9 Crore            1
55.2 Lac             1
10.65 Crore          1
8.11 Crore           1
13.75 Crore          1
8.51 Crore           1
25.51 Crore          1
4.19 Crore           1
8.15 Crore           1
93.6 Lac             1
11.86 Crore          1
8.7 Crore            1
3.23 Crore           1
3.16 Crore           1
1.74 Crore           1
14.15 Crore          1
1.94 Crore           1
99 Lac               1
1.99 Crore           1
3.99 Crore           1
21.28 Crore          1
8.9 Crore            1
5.62 Crore           1
8.13 Crore           1
2.31 Crore           1
2.11 Crore           1
6.33 Crore           1
37 Crore             1
4.88 Crore           1
2.62 Crore           1
3.83 Crore           1
5.81 Crore           1
5.28 Crore           1
8.05 Crore           1
2.49 Crore           1
51 Lac               1
9.7 Crore            1
78 Lac               1
9 Lac                1
58 Lac               1
13 Lac               1
3.77 Crore           1
6.43 Crore           1
4.37 Crore           1
9.85 Crore           1
19.25 Crore          1
15.5 Crore           1
3.53 Crore           1
5.33 Crore           1
1.07 Crore           1
75.4 Lac             1
8.38 Crore           1
4.57 Crore           1
24.5 Lac             1
6.49 Crore           1
2.69 Crore           1
12.45 Crore          1
9.54 Crore           1
7.05 Crore           1
10.63 Crore          1
6.08 Crore           1
6.16 Crore           1
11.3 Crore           1
2.56 Crore           1
8.66 Crore           1
7.33 Crore           1
4.61 Crore           1
7.03 Crore           1
25 Crore             1
9.48 Crore           1
8.82 Crore           1
79.5 Lac             1
97.5 Lac             1
1.69 Crore           1
38.94 Lac            1
6.27 Crore           1
7.7 Crore            1
9.23 Crore           1
35 Crore             1
9.96 Crore           1
7.2 Lac              1
18.9 Crore           1
94.2 Lac             1
70.4 Lac             1
68.2 Lac             1
6.41 Crore           1
7.63 Crore           1
2.33 Crore           1
7.09 Crore           1
4.92 Crore           1
2.19 Crore           1
12.2 Crore           1
6.32 Crore           1
6.35 Crore           1
88.9 Lac             1
2.72 Crore           1
4.68 Crore           1
1.37 Crore           1
1.84 Crore           1
2.59 Crore           1
18 Crore             1
5.38 Crore           1
2.74 Crore           1
3.76 Crore           1
10.79 Crore          1
22.8 Lac             1
10.26 Crore          1
38 Lac               1
8.5 Lac              1
34 Crore             1
5.68 Crore           1
96.05 Lac            1
36 Lac               1
1.91 Crore           1
23.51 Lac            1
67.5 Lac             1
3.46 Crore           1
1.42 Crore           1
5.54 Crore           1
1.59 Crore           1
49.92 Lac            1
8.98 Crore           1
7 Lac                1
3 Lac                1
3.7 Lac              1
51.25 Lac            1
10 Lac               1
9.04 Crore           1
3.12 Crore           1
3.91 Crore           1
7.12 Crore           1
8.01 Crore           1
9.95 Crore           1
8.26 Crore           1
2.39 Crore           1
4.62 Crore           1
2.65 Crore           1
5.34 Crore           1
4.58 Crore           1
2.94 Crore           1
55.31 Lac            1
20.28 Lac            1
32.4 Lac             1
3.42 Crore           1
91.5 Lac             1
14 Lac               1
6.69 Crore           1
69 Lac               1
1.5 Lac              1
43 Lac               1
22 Lac               1
5.27 Crore           1
7.4 Crore            1
3.43 Crore           1
6.87 Crore           1
5.57 Crore           1
9.92 Crore           1
33.2 Lac             1
3.55 Crore           1
6.2 Crore            1
98.45 Lac            1
3.69 Crore           1
8.85 Crore           1
5.72 Crore           1
2.17 Crore           1
1.23 Crore           1
12.5 Lac             1
41 Lac               1
52.5 Lac             1
9.55 Crore           1
9.6 Crore            1
65.4 Lac             1
2.02 Crore           1
2.27 Crore           1
78.1 Lac             1
1.83 Crore           1
5.11 Crore           1
6.66 Crore           1
68 Lac               1
39 Lac               1
5.56 Crore           1
95.7 Lac             1
6.95 Crore           1
12.6 Lac             1
2.82 Crore           1
Name: count, dtype: int64

In [23]:
df = df[~(df['price'] == 'Price on Request')]

In [25]:
df.shape

(2390, 8)

In [26]:
def price_convert(x):
  if type(x) == float or type(x) == int:
    return x
  else :
    if x[1] == 'Lac':
      return round(float(x[0])/100,2)
    else :
      return round(float(x[0]),2)

In [29]:
df['price'] = df['price'].str.split(' ').apply(price_convert)

In [31]:
df['areaWithType'].value_counts()

areaWithType
(84 sq.m.) Plot Area          99
(251 sq.m.) Plot Area         81
(420 sq.m.) Plot Area         77
(209 sq.m.) Plot Area         76
(151 sq.m.) Plot Area         74
(220 sq.m.) Plot Area         61
(201 sq.m.) Plot Area         59
(418 sq.m.) Plot Area         58
(125 sq.m.) Plot Area         51
(135 sq.m.) Plot Area         50
(301 sq.m.) Plot Area         46
(286 sq.m.) Plot Area         46
(167 sq.m.) Plot Area         45
(50 sq.m.) Plot Area          45
(226 sq.m.) Plot Area         38
(180 sq.m.) Plot Area         37
(171 sq.m.) Plot Area         33
(435 sq.m.) Plot Area         27
(293 sq.m.) Plot Area         26
(150 sq.m.) Plot Area         24
(334 sq.m.) Plot Area         24
(100 sq.m.) Plot Area         24
(17 sq.m.) Plot Area          21
(105 sq.m.) Plot Area         21
(134 sq.m.) Plot Area         20
(223 sq.m.) Plot Area         19
(110 sq.m.) Plot Area         18
(836 sq.m.) Plot Area         18
(42 sq.m.) Plot Area          18
(9 sq.m.) Plot Area           17
(130 sq.m.) Plot Area         16
(253 sq.m.) Plot Area         15
(264 sq.m.) Plot Area         15
(90 sq.m.) Plot Area          14
(250 sq.m.) Plot Area         14
(96 sq.m.) Plot Area          13
(117 sq.m.) Plot Area         13
(145 sq.m.) Plot Area         13
(188 sq.m.) Plot Area         12
(149 sq.m.) Plot Area         12
(161 sq.m.) Plot Area         11
(107 sq.m.) Plot Area         11
(450 sq.m.) Plot Area         10
(98 sq.m.) Plot Area          10
(67 sq.m.) Plot Area          10
(140 sq.m.) Plot Area         10
(23 sq.m.) Plot Area          10
(115 sq.m.) Plot Area         10
(184 sq.m.) Plot Area          9
(109 sq.m.) Plot Area          9
(11 sq.m.) Plot Area           9
(350 sq.m.) Plot Area          9
(336 sq.m.) Plot Area          9
(28 sq.m.) Plot Area           9
(94 sq.m.) Plot Area           9
(153 sq.m.) Plot Area          9
(25 sq.m.) Plot Area           9
(4047 sq.m.) Plot Area         9
(92 sq.m.) Plot Area           9
(120 sq.m.) Plot Area          8
(300 sq.m.) Plot Area          8
(136 sq.m.) Plot Area          8
(151-418 sq.m.) Plot Area      8
(142 sq.m.) Plot Area          8
(234 sq.m.) Plot Area          8
(146 sq.m.) Plot Area          8
(669 sq.m.) Plot Area          7
(138 sq.m.) Plot Area          7
(14 sq.m.) Plot Area           7
(104 sq.m.) Plot Area          7
(124 sq.m.) Plot Area          7
(46 sq.m.) Plot Area           7
(159 sq.m.) Plot Area          7
(222 sq.m.) Plot Area          7
(87 sq.m.) Plot Area           6
(52 sq.m.) Plot Area           6
(585 sq.m.) Plot Area          6
(75 sq.m.) Plot Area           6
(19 sq.m.) Plot Area           6
(230 sq.m.) Plot Area          6
(148 sq.m.) Plot Area          6
(127 sq.m.) Plot Area          6
(207 sq.m.) Plot Area          6
(166 sq.m.) Plot Area          6
(276 sq.m.) Plot Area          6
(225 sq.m.) Plot Area          6
(227 sq.m.) Plot Area          6
(15 sq.m.) Plot Area           6
(299 sq.m.) Plot Area          6
(46-402 sq.m.) Plot Area       5
(539 sq.m.) Plot Area          5
(356 sq.m.) Plot Area          5
(99 sq.m.) Plot Area           5
(51 sq.m.) Plot Area           5
(89 sq.m.) Plot Area           5
(85 sq.m.) Plot Area           5
(152 sq.m.) Plot Area          5
(65 sq.m.) Plot Area           5
(12 sq.m.) Plot Area           5
(101 sq.m.) Plot Area          5
(251-523 sq.m.) Plot Area      5
(216 sq.m.) Plot Area          5
(855 sq.m.) Plot Area          5
(314 sq.m.) Plot Area          5
(123 sq.m.) Plot Area          4
(460 sq.m.) Plot Area          4
(113 sq.m.) Plot Area          4
(219 sq.m.) Plot Area          4
(217 sq.m.) Plot Area          4
(18 sq.m.) Plot Area           4
(6 sq.m.) Plot Area            4
(252 sq.m.) Plot Area          4
(164 sq.m.) Plot Area          4
(8094 sq.m.) Plot Area         4
(111 sq.m.) Plot Area          4
(118 sq.m.) Plot Area          4
(103 sq.m.) Plot Area          4
(210 sq.m.) Plot Area          4
(7 sq.m.) Plot Area            4
(126 sq.m.) Plot Area          4
(268 sq.m.) Plot Area          4
(414 sq.m.) Plot Area          4
(112-148 sq.m.) Plot Area      4
(107-150 sq.m.) Plot Area      4
(114 sq.m.) Plot Area          4
(209-334 sq.m.) Plot Area      4
(144 sq.m.) Plot Area          4
(167-420 sq.m.) Plot Area      4
(329 sq.m.) Plot Area          4
(66 sq.m.) Plot Area           4
(216-585 sq.m.) Plot Area      4
(151-836 sq.m.) Plot Area      4
(242 sq.m.) Plot Area          4
(69 sq.m.) Plot Area           3
(421 sq.m.) Plot Area          3
(70 sq.m.) Plot Area           3
(174 sq.m.) Plot Area          3
(54 sq.m.) Plot Area           3
(50-151 sq.m.) Plot Area       3
(32 sq.m.) Plot Area           3
(627 sq.m.) Plot Area          3
(60 sq.m.) Plot Area           3
(202 sq.m.) Plot Area          3
(393 sq.m.) Plot Area          3
(247 sq.m.) Plot Area          3
(143 sq.m.) Plot Area          3
(680 sq.m.) Plot Area          3
(73 sq.m.) Plot Area           3
(93 sq.m.) Plot Area           3
(105-146 sq.m.) Plot Area      3
(82 sq.m.) Plot Area           3
(131 sq.m.) Plot Area          3
(119 sq.m.) Plot Area          3
(121 sq.m.) Plot Area          3
(490 sq.m.) Plot Area          3
(261 sq.m.) Plot Area          3
(218 sq.m.) Plot Area          3
(108 sq.m.) Plot Area          3
(155 sq.m.) Plot Area          3
(102 sq.m.) Plot Area          3
(20234 sq.m.) Plot Area        3
(297 sq.m.) Plot Area          3
(22 sq.m.) Plot Area           3
(100-150 sq.m.) Plot Area      3
(88-111 sq.m.) Plot Area       3
(125-620 sq.m.) Plot Area      3
(644 sq.m.) Plot Area          3
(128 sq.m.) Plot Area          3
(16 sq.m.) Plot Area           3
(63 sq.m.) Plot Area           3
(165 sq.m.) Plot Area          3
(376 sq.m.) Plot Area          2
(16187 sq.m.) Plot Area        2
(55 sq.m.) Plot Area           2
(141 sq.m.) Plot Area          2
(103-140 sq.m.) Plot Area      2
(167-358 sq.m.) Plot Area      2
(47 sq.m.) Plot Area           2
(129 sq.m.) Plot Area          2
(40469 sq.m.) Plot Area        2
(324 sq.m.) Plot Area          2
(154 sq.m.) Plot Area          2
(221 sq.m.) Plot Area          2
(1208 sq.m.) Plot Area         2
(312 sq.m.) Plot Area          2
(430 sq.m.) Plot Area          2
(162 sq.m.) Plot Area          2
(809 sq.m.) Plot Area          2
(108-150 sq.m.) Plot Area      2
(125-151 sq.m.) Plot Area      2
(6070 sq.m.) Plot Area         2
(81 sq.m.) Plot Area           2
(344 sq.m.) Plot Area          2
(307 sq.m.) Plot Area          2
(190 sq.m.) Plot Area          2
(325 sq.m.) Plot Area          2
(237 sq.m.) Plot Area          2
(212 sq.m.) Plot Area          2
(570 sq.m.) Plot Area          2
(291 sq.m.) Plot Area          2
(134-150 sq.m.) Plot Area      2
(117-150 sq.m.) Plot Area      2
(335 sq.m.) Plot Area          2
(201-301 sq.m.) Plot Area      2
(201-836 sq.m.) Plot Area      2
(452 sq.m.) Plot Area          2
(32-1007 sq.m.) Plot Area      2
(156 sq.m.) Plot Area          2
(178 sq.m.) Plot Area          2
(77 sq.m.) Plot Area           2
(203 sq.m.) Plot Area          2
(390 sq.m.) Plot Area          2
(353 sq.m.) Plot Area          2
(20 sq.m.) Plot Area           2
(258 sq.m.) Plot Area          2
(224 sq.m.) Plot Area          2
(244 sq.m.) Plot Area          2
(213 sq.m.) Plot Area          2
(18211 sq.m.) Plot Area        2
(100-149 sq.m.) Plot Area      2
(71-155 sq.m.) Plot Area       2
(158 sq.m.) Plot Area          2
(910 sq.m.) Plot Area          2
(512 sq.m.) Plot Area          2
(95 sq.m.) Plot Area           2
(168 sq.m.) Plot Area          2
(196 sq.m.) Plot Area          2
(71 sq.m.) Plot Area           2
(439 sq.m.) Plot Area          2
(192 sq.m.) Plot Area          2
(466 sq.m.) Plot Area          2
(176 sq.m.) Plot Area          2
(288 sq.m.) Plot Area          2
(263 sq.m.) Plot Area          2
(147 sq.m.) Plot Area          2
(50-403 sq.m.) Plot Area       2
(330 sq.m.) Plot Area          2
(177 sq.m.) Plot Area          2
(1672 sq.m.) Plot Area         2
(139 sq.m.) Plot Area          1
(841 sq.m.) Plot Area          1
(637 sq.m.) Plot Area          1
(416 sq.m.) Plot Area          1
(554 sq.m.) Plot Area          1
(920 sq.m.) Plot Area          1
(86 sq.m.) Plot Area           1
(137 sq.m.) Plot Area          1
(326 sq.m.) Plot Area          1
(1138 sq.m.) Plot Area         1
(163 sq.m.) Plot Area          1
(257 sq.m.) Plot Area          1
(323 sq.m.) Plot Area          1
(616 sq.m.) Plot Area          1
(564 sq.m.) Plot Area          1
(287 sq.m.) Plot Area          1
(538 sq.m.) Plot Area          1
(647497 sq.m.) Plot Area       1
(43 sq.m.) Plot Area           1
(2090 sq.m.) Plot Area         1
(2174 sq.m.) Plot Area         1
(2508 sq.m.) Plot Area         1
(431 sq.m.) Plot Area          1
(559 sq.m.) Plot Area          1
(346 sq.m.) Plot Area          1
(698 sq.m.) Plot Area          1
(294 sq.m.) Plot Area          1
(690 sq.m.) Plot Area          1
(80937 sq.m.) Plot Area        1
(24 sq.m.) Plot Area           1
(212-920 sq.m.) Plot Area      1
(10 sq.m.) Plot Area           1
(205 sq.m.) Plot Area          1
(691 sq.m.) Plot Area          1
(413 sq.m.) Plot Area          1
(4667 sq.m.) Plot Area         1
(399 sq.m.) Plot Area          1
(200 sq.m.) Plot Area          1
(278 sq.m.) Plot Area          1
(76 sq.m.) Plot Area           1
(318 sq.m.) Plot Area          1
(170 sq.m.) Plot Area          1
(4064 sq.m.) Plot Area         1
(309 sq.m.) Plot Area          1
(500 sq.m.) Plot Area          1
(28328 sq.m.) Plot Area        1
(319 sq.m.) Plot Area          1
(95-105 sq.m.) Plot Area       1
(216-247 sq.m.) Plot Area      1
(151-188 sq.m.) Plot Area      1
(101-161 sq.m.) Plot Area      1
(105-121 sq.m.) Plot Area      1
(338 sq.m.) Plot Area          1
(109-142 sq.m.) Plot Area      1
(110-836 sq.m.) Plot Area      1
(201-418 sq.m.) Plot Area      1
(50-149 sq.m.) Plot Area       1
(153-418 sq.m.) Plot Area      1
(511 sq.m.) Plot Area          1
(265 sq.m.) Plot Area          1
(700 sq.m.) Plot Area          1
(890 sq.m.) Plot Area          1
(510 sq.m.) Plot Area          1
(272 sq.m.) Plot Area          1
(341 sq.m.) Plot Area          1
(24281 sq.m.) Plot Area        1
(64 sq.m.) Plot Area           1
(308 sq.m.) Plot Area          1
(167-284 sq.m.) Plot Area      1
(125-141 sq.m.) Plot Area      1
(124-151 sq.m.) Plot Area      1
(107-148 sq.m.) Plot Area      1
(73-149 sq.m.) Plot Area       1
(543 sq.m.) Plot Area          1
(223-418 sq.m.) Plot Area      1
(223-470 sq.m.) Plot Area      1
(331 sq.m.) Plot Area          1
(358 sq.m.) Plot Area          1
(236 sq.m.) Plot Area          1
(838 sq.m.) Plot Area          1
(1012 sq.m.) Plot Area         1
(290 sq.m.) Plot Area          1
(388 sq.m.) Plot Area          1
(255 sq.m.) Plot Area          1
(434 sq.m.) Plot Area          1
(451 sq.m.) Plot Area          1
(32-72 sq.m.) Plot Area        1
(752-8094 sq.m.) Plot Area     1
(151-560 sq.m.) Plot Area      1
(209-928 sq.m.) Plot Area      1
(59 sq.m.) Plot Area           1
(368 sq.m.) Plot Area          1
(645 sq.m.) Plot Area          1
(266 sq.m.) Plot Area          1
(887 sq.m.) Plot Area          1
(930 sq.m.) Plot Area          1
(424 sq.m.) Plot Area          1
(613 sq.m.) Plot Area          1
(4515 sq.m.) Plot Area         1
(204 sq.m.) Plot Area          1
(673 sq.m.) Plot Area          1
(72 sq.m.) Plot Area           1
(232 sq.m.) Plot Area          1
(123-151 sq.m.) Plot Area      1
(491 sq.m.) Plot Area          1
(29 sq.m.) Plot Area           1
(273 sq.m.) Plot Area          1
(885 sq.m.) Plot Area          1
(527 sq.m.) Plot Area          1
(355 sq.m.) Plot Area          1
(661 sq.m.) Plot Area          1
(296 sq.m.) Plot Area          1
(594 sq.m.) Plot Area          1
(208 sq.m.) Plot Area          1
(481 sq.m.) Plot Area          1
(899 sq.m.) Plot Area          1
(160 sq.m.) Plot Area          1
(502 sq.m.) Plot Area          1
(44 sq.m.) Plot Area           1
(6475 sq.m.) Plot Area         1
(372 sq.m.) Plot Area          1
(0 sq.m.) Plot Area            1
(260 sq.m.) Plot Area          1
(405 sq.m.) Plot Area          1
(441 sq.m.) Plot Area          1
(132 sq.m.) Plot Area          1
(364 sq.m.) Plot Area          1
(283 sq.m.) Plot Area          1
(1254 sq.m.) Plot Area         1
(4 sq.m.) Plot Area            1
(254 sq.m.) Plot Area          1
(381 sq.m.) Plot Area          1
(106 sq.m.) Plot Area          1
(33 sq.m.) Plot Area           1
(77-121 sq.m.) Plot Area       1
(167-277 sq.m.) Plot Area      1
(84-151 sq.m.) Plot Area       1
(147-151 sq.m.) Plot Area      1
(231 sq.m.) Plot Area          1
(426 sq.m.) Plot Area          1
(197 sq.m.) Plot Area          1
(194 sq.m.) Plot Area          1
(412 sq.m.) Plot Area          1
(343 sq.m.) Plot Area          1
(462 sq.m.) Plot Area          1
(385 sq.m.) Plot Area          1
(277 sq.m.) Plot Area          1
(688 sq.m.) Plot Area          1
(468 sq.m.) Plot Area          1
(600 sq.m.) Plot Area          1
(214 sq.m.) Plot Area          1
(14164 sq.m.) Plot Area        1
(1619 sq.m.) Plot Area         1
(8633 sq.m.) Plot Area         1
(3716 sq.m.) Plot Area         1
(172 sq.m.) Plot Area          1
(68 sq.m.) Plot Area           1
(1463 sq.m.) Plot Area         1
(83 sq.m.) Plot Area           1
(284 sq.m.) Plot Area          1
(369 sq.m.) Plot Area          1
(648 sq.m.) Plot Area          1
(12141 sq.m.) Plot Area        1
(15176 sq.m.) Plot Area        1
(186 sq.m.) Plot Area          1
(302 sq.m.) Plot Area          1
(446 sq.m.) Plot Area          1
(48 sq.m.) Plot Area           1
(839 sq.m.) Plot Area          1
(932 sq.m.) Plot Area          1
(122 sq.m.) Plot Area          1
(72843 sq.m.) Plot Area        1
(183 sq.m.) Plot Area          1
(5 sq.m.) Plot Area            1
(8 sq.m.) Plot Area            1
(1129 sq.m.) Plot Area         1
Name: count, dtype: int64

In [47]:
df.rename(columns={'noOfOpenSides':'open_sides','floorNumAllowed':'floor_num'},inplace = True)

In [53]:
df.sample(1)

,property_name,society,price,areaWithType,floor_num,open_sides,possession,features
534,Residential land / Plot in Sector 57 Gurgaon,nan,4.6,(220 sq.m.) Plot Area,4,1.0,Immediate,NaN

In [58]:
df.sample(5)

,property_name,society,price,areaWithType,floor_num,open_sides,possession,features
2163,Residential land / Plot in Sector 67 Gurgaon,ansal api esencia,5.95,(293 sq.m.) Plot Area,NaN,1.0,Immediate,"[['Feng Shui / Vaastu Compliant', 'Maintenance..."
1037,Residential land / Plot in Sushant Lok Phase 2,nan,2.59,(146 sq.m.) Plot Area,NaN,1.0,NaN,"[['Feng Shui / Vaastu Compliant', 'Maintenance..."
331,Residential land / Plot in Sector 73 Gurgaon,dlf alameda,11.86,(451 sq.m.) Plot Area,NaN,1.0,Immediate,NaN
2031,Residential land / Plot in Maruti Kunj,mrs 16 acres,0.15,(84 sq.m.) Plot Area,4,1.0,Immediate,"[['Feng Shui / Vaastu Compliant', 'Maintenance..."
1143,Residential land / Plot in Palam Vihar,ansals palam vihar,6.65,(435 sq.m.) Plot Area,4,NaN,Immediate,"[['Feng Shui / Vaastu Compliant', 'Rain Water ..."

In [59]:
df.to_csv('residential_land_cleaned.csv',index=False)